version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    image: discord-tech-news-bot:latest
    container_name: discord-tech-news-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://discord.com', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge 